### ISSUE TITLE
Possibly use common-tags to deal with the indentation

### ISSUE THREAD

**Issue by saadq** [nitin42/stylus-in-react#1]
Hey, awesome package I've really been wanting something like this. You've already mentioned the caveat with this project where you can't have leading indentation. If you haven't already, I would recommend checking out the [`common-tags`](https://github.com/declandewet/common-tags) package which is a utility library for dealing with template literals. I think the [`stripIndent`](https://github.com/declandewet/common-tags#stripindent) might be of use here. What do you think?

**Comment by nitin42** [comment]
Sound's interesting! Do you want to try this ? That'd be great!

**Comment by nitin42** [comment]
Closing because it's done and thanks for the suggestion, it really worked!
